# Generated by Django 6.0.3 on 2026-03-05 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('configured', 'Configured'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20)),
                ('pptx_file', models.FileField(blank=True, null=True, upload_to='presentations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectivesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_title', models.CharField(max_length=255)),
                ('audience', models.CharField(max_length=50)),
                ('tone', models.CharField(max_length=50)),
                ('primary_objectives', models.JSONField(default=list)),
                ('key_metrics', models.JSONField(default=list)),
                ('comparison_dimensions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('finding', models.TextField()),
                ('magnitude', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('data_slice', models.JSONField(default=dict)),
                ('chart_hint', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='api.project')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data_files/')),
                ('file_type', models.CharField(max_length=10)),
                ('column_map', models.JSONField(default=dict)),
                ('profile', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('slide_index_affected', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rfp_docs/')),
                ('file_type', models.CharField(max_length=10)),
                ('parsed_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfp_document', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_index', models.IntegerField()),
                ('slide_type', models.CharField(choices=[('title', 'Title'), ('overview', 'Overview'), ('chart', 'Chart'), ('insight', 'Insight'), ('comparison', 'Comparison'), ('executive_summary', 'Executive Summary'), ('recommendation', 'Recommendation'), ('data_table', 'Data Table')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('narrative', models.TextField(blank=True)),
                ('chart_png', models.ImageField(blank=True, null=True, upload_to='charts/')),
                ('bullet_points', models.JSONField(default=list)),
                ('speaker_notes', models.TextField(blank=True)),
                ('insight_ids', models.JSONField(default=list)),
                ('chart_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.project')),
            ],
            options={
                'ordering': ['slide_index'],
            },
        ),
    ]
