# Generated by Django 6.0.3 on 2026-03-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='chart_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
