# Generated by Django 6.0.3 on 2026-03-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_chart_json_to_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='relationship_graph',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datafile',
            name='sheet_classifications',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datafile',
            name='sheet_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datafile',
            name='summary_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='BriefDecomposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_context', models.TextField()),
                ('analytical_questions', models.JSONField(default=list)),
                ('audience_and_tone', models.TextField()),
                ('full_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='SheetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50)),
                ('sheet_names', models.JSONField(default=list)),
                ('join_keys', models.JSONField(default=dict)),
                ('analytical_framing', models.TextField(blank=True)),
                ('insight_scan_raw', models.JSONField(default=dict)),
                ('drill_down_results', models.JSONField(default=dict)),
                ('insights_extracted', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_groups', to='api.project')),
            ],
            options={
                'ordering': ['group_id'],
            },
        ),
    ]
